name: Auto Deploy React App

on:
  push:
    branches:
      - main  # Trigger this action only on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'  # Adjust the node version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React application
      - name: Build React App
        run: npm run build

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}   # Set this in the GitHub repository secrets
          username: ${{ secrets.EC2_USER }} # Set this in the GitHub repository secrets
          key: ${{ secrets.EC2_SSH_KEY }}      # Set your EC2 private key in the GitHub secrets
          script: |
            cd /home/ubuntu/show-and-go-F           # Navigate to the app directory on the server
            git pull origin main           # Pull latest changes
            npm install                    # Install dependencies
            npm run build                  # Build the React app
            sudo systemctl restart nginx   # Restart Nginx to serve the latest version
